version: "3"
services:
  hub:
    image: selenium/hub:4.1.0
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.1.0
    shm_size: '2gb'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1
    volumes:
      - ./downloads:/home/seluser/Downloads
  firefox:
    image: selenium/node-firefox:4.1.0
    shm_size: '2gb'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - ./downloads:/home/seluser/Downloads